### ISSUE TITLE
Error: Undefined variable.

### ISSUE THREAD

**Issue by normal-coder** [yuncishuzi/iui-design#13]
### iui-design 版本

latest

### 重现步骤

CLI 初始化项目后，安装并运行。提示报错

```
05:01:28.650 [plugin:vite:css] Undefined variable.
05:01:28.663   ╷
05:01:28.663 2 │     #{$prefix}-primary-1: #{$primary-color-1};
05:01:28.675   │       ^^^^^^^
05:01:28.687   ╵
05:01:28.701   node_modules/iui-design/style/color/variables.scss 2:7   lightMode()
05:01:28.701   node_modules/iui-design/style/color/variables.scss 70:5  @import
05:01:28.716   node_modules/iui-design/style/index.scss 2:9             @import
05:01:28.730   src/App.vue 79:13                                        root stylesheet
05:01:28.742 at App.vue:1:0
05:01:28.742   Error: Undefined variable.
05:01:28.754     ╷
05:01:28.755   2 │     #{$prefix}-primary-1: #{$primary-color-1};
05:01:28.768     │       ^^^^^^^
05:01:28.782     ╵
05:01:28.783     node_modules/iui-design/style/color/variables.scss 2:7   lightMode()
05:01:28.796     node_modules/iui-design/style/color/variables.scss 70:5  @import
05:01:28.809     node_modules/iui-design/style/index.scss 2:9             @import
05:01:28.822     src/App.vue 79:13                                        root stylesheet
05:01:28.822 [plugin:vite:css] Undefined variable.
05:01:28.836   ╷
05:01:28.851 2 │     #{$prefix}-primary-1: #{$primary-color-1};
05:01:28.868   │       ^^^^^^^
05:01:28.868   ╵
05:01:28.882   node_modules/iui-design/style/color/variables.scss 2:7   lightMode()
05:01:28.913   node_modules/iui-design/style/color/variables.scss 70:5  @import
05:01:28.926   node_modules/iui-design/style/index.scss 2:9             @import
05:01:28.926   src/App.vue 79:13                                        root stylesheet
05:01:28.940 at App.vue:1:0
05:01:28.954   Error: Undefined variable.
05:01:28.967     ╷
05:01:28.968   2 │     #{$prefix}-primary-1: #{$primary-color-1};
05:01:28.983     │       ^^^^^^^
05:01:29.013     ╵
05:01:29.027     node_modules/iui-design/style/color/variables.scss 2:7   lightMode()
05:01:29.027     node_modules/iui-design/style/color/variables.scss 70:5  @import
05:01:29.041     node_modules/iui-design/style/index.scss 2:9             @import
05:01:29.056     src/App.vue 79:13                                        root stylesheet
```

### 期望结果

修复未定义的变量

### 框架版本

"@dcloudio/uni-app": "3.0.0-3081220230817001"

### 运行平台

App

**Comment by nobu121** [comment]
你好，请检查在 uni.scss 中是否导入主题变量
```scss
// npm 模式安装
@import "iui-design/style/theme.scss";

// HBuilderX 插件市场安装
@import "@/components/iui-design/style/theme.scss";
```

**Comment by normal-coder** [comment]
过了一会儿就正常了。。。
